package com.mybank.global.risk.credit;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class CreditApplication implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	private java.lang.String vorgangID;
	private java.lang.Boolean appoved;

	private java.util.Date referenceDate;

	public CreditApplication() {
	}

	public java.lang.String getVorgangID() {
		return this.vorgangID;
	}

	public void setVorgangID(java.lang.String vorgangID) {
		this.vorgangID = vorgangID;
	}

	public java.lang.Boolean getAppoved() {
		return this.appoved;
	}

	public void setAppoved(java.lang.Boolean appoved) {
		this.appoved = appoved;
	}

	public java.util.Date getReferenceDate() {
		return this.referenceDate;
	}

	public void setReferenceDate(java.util.Date referenceDate) {
		this.referenceDate = referenceDate;
	}

	public CreditApplication(java.lang.String vorgangID,
			java.lang.Boolean appoved, java.util.Date referenceDate) {
		this.vorgangID = vorgangID;
		this.appoved = appoved;
		this.referenceDate = referenceDate;
	}

}