package com.mybank.global.risk.credit;

/**
 * This class was automatically generated by the data modeler tool.
 */

@javax.persistence.Entity
public class KOCriterion implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	@javax.persistence.GeneratedValue(generator = "KO_KRITERIUM_ID_GENERATOR", strategy = javax.persistence.GenerationType.AUTO)
	@javax.persistence.Id
	@javax.persistence.SequenceGenerator(sequenceName = "KO_KRITERIUM_ID_SEQ", name = "KO_KRITERIUM_ID_GENERATOR")
	private java.lang.Long id;

	private java.lang.String explanation;

	private java.lang.Boolean isSoftKO;

	public KOCriterion() {
	}

	public java.lang.Long getId() {
		return this.id;
	}

	public void setId(java.lang.Long id) {
		this.id = id;
	}

	public java.lang.String getExplanation() {
		return this.explanation;
	}

	public void setExplanation(java.lang.String explanation) {
		this.explanation = explanation;
	}

	public java.lang.Boolean getIsSoftKO() {
		return this.isSoftKO;
	}

	public void setIsSoftKO(java.lang.Boolean isSoftKO) {
		this.isSoftKO = isSoftKO;
	}

	public KOCriterion(java.lang.Long id, java.lang.String explanation,
			java.lang.Boolean isSoftKO) {
		this.id = id;
		this.explanation = explanation;
		this.isSoftKO = isSoftKO;
	}

}