package com.mybank.global.risk.credit;

import java.util.Date;

/**
 * This class was automatically generated by the data modeler tool.
 */

@javax.persistence.Entity
public class Person implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	@javax.persistence.GeneratedValue(strategy = javax.persistence.GenerationType.AUTO, generator = "PERSON_ID_GENERATOR")
	@javax.persistence.Id
	@javax.persistence.SequenceGenerator(sequenceName = "PERSON_ID_SEQ", name = "PERSON_ID_GENERATOR")
	private java.lang.Long id;

	private java.lang.String asType;

	private java.lang.String occupation;

	private java.util.Date occupationStartDate;

	private java.lang.String industryType;

	private java.util.Date birthDate;

	public Person() {
	}

	public java.lang.Long getId() {
		return this.id;
	}

	public void setId(java.lang.Long id) {
		this.id = id;
	}

	public java.lang.String getAsType() {
		return this.asType;
	}

	public void setAsType(java.lang.String asType) {
		this.asType = asType;
	}

	public java.lang.String getOccupation() {
		return this.occupation;
	}

	public void setOccupation(java.lang.String occupation) {
		this.occupation = occupation;
	}

	public java.util.Date getOccupationStartDate() {
		return this.occupationStartDate;
	}

	public void setOccupationStartDate(java.util.Date occupationStatDate) {
		this.occupationStartDate = occupationStartDate;
	}

	public java.lang.String getIndustryType() {
		return this.industryType;
	}

	public void setIndustryType(java.lang.String industryType) {
		this.industryType = industryType;
	}

	public java.util.Date getBirthDate() {
		return this.birthDate;
	}

	public void setBirthDate(java.util.Date birthDate) {
		this.birthDate = birthDate;
	}

	public Person(java.lang.Long id, java.lang.String asType,
			java.lang.String occupation, java.util.Date occupationStartDate,
			java.lang.String industryType, java.util.Date birthDate) {
		this.id = id;
		this.asType = asType;
		this.occupation = occupation;
		this.occupationStartDate = occupationStartDate;
		this.industryType = industryType;
		this.birthDate = birthDate;
	}

}