package com.mybank.global.risk.credit;

/**
 * This class was automatically generated by the data modeler tool.
 */

@javax.persistence.Entity
public class ScoringResult implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	@javax.persistence.GeneratedValue(strategy = javax.persistence.GenerationType.AUTO, generator = "SCORINGRESULT_ID_GENERATOR")
	@javax.persistence.Id
	@javax.persistence.SequenceGenerator(sequenceName = "SCORINGRESULT_ID_SEQ", name = "SCORINGRESULT_ID_GENERATOR")
	private java.lang.Long id;

	private java.lang.String characteristic;

	private java.lang.Integer ruleNumber;

	private java.lang.Integer points;

	public ScoringResult() {
	}

	public java.lang.Long getId() {
		return this.id;
	}

	public void setId(java.lang.Long id) {
		this.id = id;
	}

	public java.lang.String getCharacteristic() {
		return this.characteristic;
	}

	public void setCharacteristic(java.lang.String characteristic) {
		this.characteristic = characteristic;
	}

	public java.lang.Integer getRuleNumber() {
		return this.ruleNumber;
	}

	public void setRuleNumber(java.lang.Integer ruleNumber) {
		this.ruleNumber = ruleNumber;
	}

	public java.lang.Integer getPoints() {
		return this.points;
	}

	public void setPoints(java.lang.Integer points) {
		this.points = points;
	}

	public ScoringResult(java.lang.Long id, java.lang.String characteristic,
			java.lang.Integer ruleNumber, java.lang.Integer points) {
		this.id = id;
		this.characteristic = characteristic;
		this.ruleNumber = ruleNumber;
		this.points = points;
	}

}