package com.mybank.global.risk.credit;

import java.math.BigDecimal;
import java.math.BigInteger;

/**
 * This class was automatically generated by the data modeler tool.
 */

@javax.persistence.Entity
public class SelfInformation implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	@javax.persistence.GeneratedValue(strategy = javax.persistence.GenerationType.AUTO, generator = "HAUSHALTSRECHNUNG_ID_GENERATOR")
	@javax.persistence.Id
	@javax.persistence.SequenceGenerator(sequenceName = "HAUSHALTSRECHNUNG_ID_SEQ", name = "HAUSHALTSRECHNUNG_ID_GENERATOR")
	private java.lang.Long id;

	private java.math.BigInteger countOfChildren;

	private java.math.BigInteger countOfPersons;

	private java.math.BigInteger countOfVehicles;

	private java.math.BigDecimal scndIncome;

	private java.math.BigDecimal income;

	private java.math.BigDecimal oldAgePension;

	private java.math.BigDecimal otherIssues;

	private java.math.BigDecimal savings;

	public SelfInformation() {
	}

	public SelfInformation(java.lang.Long id) {
		this.id = id;
	}

	public java.lang.Long getId() {
		return this.id;
	}

	public void setId(java.lang.Long id) {
		this.id = id;
	}

	private BigDecimal sonstigeAusgaben;
	public BigDecimal getSonstigeAusgaben() {
		return sonstigeAusgaben;
	}

	public void setSonstigeAusgaben(final BigDecimal sonstigeAusgaben) {
		this.sonstigeAusgaben = sonstigeAusgaben;
	}

	public java.math.BigInteger getCountOfChildren() {
		return this.countOfChildren;
	}

	public void setCountOfChildren(java.math.BigInteger countOfChildren) {
		this.countOfChildren = countOfChildren;
	}

	public java.math.BigInteger getCountOfPersons() {
		return this.countOfPersons;
	}

	public void setCountOfPersons(java.math.BigInteger countOfPersons) {
		this.countOfPersons = countOfPersons;
	}

	public java.math.BigInteger getCountOfVehicles() {
		return this.countOfVehicles;
	}

	public void setCountOfVehicles(java.math.BigInteger countOfVehicles) {
		this.countOfVehicles = countOfVehicles;
	}

	public java.math.BigDecimal getScndIncome() {
		return this.scndIncome;
	}

	public void setScndIncome(java.math.BigDecimal scndIncome) {
		this.scndIncome = scndIncome;
	}

	public java.math.BigDecimal getIncome() {
		return this.income;
	}

	public void setIncome(java.math.BigDecimal income) {
		this.income = income;
	}

	public java.math.BigDecimal getOldAgePension() {
		return this.oldAgePension;
	}

	public void setOldAgePension(java.math.BigDecimal oldAgePension) {
		this.oldAgePension = oldAgePension;
	}

	public java.math.BigDecimal getOtherIssues() {
		return this.otherIssues;
	}

	public void setOtherIssues(java.math.BigDecimal otherIssues) {
		this.otherIssues = otherIssues;
	}

	public java.math.BigDecimal getSavings() {
		return this.savings;
	}

	public void setSavings(java.math.BigDecimal savings) {
		this.savings = savings;
	}

	public SelfInformation(java.lang.Long id,
			java.math.BigInteger countOfChildren,
			java.math.BigInteger countOfPersons,
			java.math.BigInteger countOfVehicles,
			java.math.BigDecimal scndIncome, java.math.BigDecimal income,
			java.math.BigDecimal oldAgePension,
			java.math.BigDecimal otherIssues, java.math.BigDecimal savings,
			java.math.BigDecimal sonstigeAusgaben) {
		this.id = id;
		this.countOfChildren = countOfChildren;
		this.countOfPersons = countOfPersons;
		this.countOfVehicles = countOfVehicles;
		this.scndIncome = scndIncome;
		this.income = income;
		this.oldAgePension = oldAgePension;
		this.otherIssues = otherIssues;
		this.savings = savings;
		this.sonstigeAusgaben = sonstigeAusgaben;
	}

}